#!/bin/bash
set -euo pipefail

# ── Only run in Claude Code web (remote) environments ───────────────
if [ "${CLAUDE_CODE_REMOTE:-}" != "true" ]; then
  exit 0
fi

# ── Java Proxy Setup ───────────────────────────────────────────────
# The cloud container routes all traffic through an HTTP proxy.
# curl uses HTTP_PROXY/HTTPS_PROXY automatically, but Java's HTTP client
# needs explicit system properties. We parse the proxy URL from the
# environment and configure Gradle's user-level gradle.properties.
configure_java_proxy() {
  local proxy_url="${HTTPS_PROXY:-${HTTP_PROXY:-}}"
  if [ -z "${proxy_url}" ]; then
    echo "No proxy configured, skipping Java proxy setup."
    return
  fi

  # Parse proxy URL: http://user:pass@host:port
  local proxy_userinfo proxy_hostport proxy_host proxy_port proxy_user proxy_pass
  # Strip protocol
  proxy_url="${proxy_url#http://}"
  proxy_url="${proxy_url#https://}"

  if [[ "${proxy_url}" == *"@"* ]]; then
    proxy_userinfo="${proxy_url%@*}"
    proxy_hostport="${proxy_url##*@}"
    proxy_user="${proxy_userinfo%%:*}"
    proxy_pass="${proxy_userinfo#*:}"
  else
    proxy_hostport="${proxy_url}"
    proxy_user=""
    proxy_pass=""
  fi

  proxy_host="${proxy_hostport%%:*}"
  proxy_port="${proxy_hostport##*:}"

  echo "Configuring Java proxy: ${proxy_host}:${proxy_port}"

  local gradle_user_home="${GRADLE_USER_HOME:-${HOME}/.gradle}"
  mkdir -p "${gradle_user_home}"

  # Write proxy settings to user-level gradle.properties
  # (not the project file — this is session-specific)
  cat > "${gradle_user_home}/gradle.properties.proxy" <<PROPEOF
# Auto-generated by session-start hook — Java proxy config
systemProp.http.proxyHost=${proxy_host}
systemProp.http.proxyPort=${proxy_port}
systemProp.https.proxyHost=${proxy_host}
systemProp.https.proxyPort=${proxy_port}
PROPEOF

  if [ -n "${proxy_user}" ]; then
    cat >> "${gradle_user_home}/gradle.properties.proxy" <<PROPEOF
systemProp.http.proxyUser=${proxy_user}
systemProp.http.proxyPassword=${proxy_pass}
systemProp.https.proxyUser=${proxy_user}
systemProp.https.proxyPassword=${proxy_pass}
systemProp.jdk.http.auth.tunneling.disabledSchemes=
PROPEOF
  fi

  # Merge into existing gradle.properties or create new
  if [ -f "${gradle_user_home}/gradle.properties" ]; then
    # Remove any existing proxy lines first
    grep -v "systemProp\.\(http\|https\)\.proxy\|systemProp\.jdk\.http\.auth" \
      "${gradle_user_home}/gradle.properties" > "${gradle_user_home}/gradle.properties.tmp" || true
    cat "${gradle_user_home}/gradle.properties.proxy" >> "${gradle_user_home}/gradle.properties.tmp"
    mv "${gradle_user_home}/gradle.properties.tmp" "${gradle_user_home}/gradle.properties"
  else
    mv "${gradle_user_home}/gradle.properties.proxy" "${gradle_user_home}/gradle.properties"
  fi
  rm -f "${gradle_user_home}/gradle.properties.proxy"

  # Also set JAVA_TOOL_OPTIONS so the Gradle wrapper JVM (before it reads
  # gradle.properties) can resolve through the proxy
  local java_proxy_opts="-Dhttp.proxyHost=${proxy_host} -Dhttp.proxyPort=${proxy_port}"
  java_proxy_opts="${java_proxy_opts} -Dhttps.proxyHost=${proxy_host} -Dhttps.proxyPort=${proxy_port}"
  if [ -n "${proxy_user}" ]; then
    java_proxy_opts="${java_proxy_opts} -Djdk.http.auth.tunneling.disabledSchemes="
    java_proxy_opts="${java_proxy_opts} -Dhttp.proxyUser=${proxy_user} -Dhttp.proxyPassword=${proxy_pass}"
    java_proxy_opts="${java_proxy_opts} -Dhttps.proxyUser=${proxy_user} -Dhttps.proxyPassword=${proxy_pass}"
  fi

  # Export for the rest of this script and persist for the session
  export JAVA_TOOL_OPTIONS="${JAVA_TOOL_OPTIONS:-} ${java_proxy_opts}"
  cat >> "${CLAUDE_ENV_FILE}" <<ENVEOF
export JAVA_TOOL_OPTIONS="\${JAVA_TOOL_OPTIONS:-} ${java_proxy_opts}"
ENVEOF
}

configure_java_proxy

# ── Android SDK Setup ───────────────────────────────────────────────
# The cloud environment has Java 21 but no Android SDK.
# This project requires: compileSdk 36, build-tools 36.0.0, platform-tools.
ANDROID_HOME="${HOME}/android-sdk"
SDK_BASE_URL="https://dl.google.com/android/repository"

download_and_extract() {
  local url="$1"
  local dest="$2"
  local tmp_zip
  tmp_zip="$(mktemp /tmp/sdk-pkg-XXXXXX.zip)"
  echo "  Downloading $(basename "${url}")..."
  curl -fsSL -o "${tmp_zip}" "${url}"
  mkdir -p "${dest}"
  unzip -q -o "${tmp_zip}" -d "${dest}"
  rm -f "${tmp_zip}"
}

install_android_sdk() {
  echo "Installing Android SDK..."

  # 1. Platform SDK (compileSdk 36)
  download_and_extract \
    "${SDK_BASE_URL}/platform-36_r02.zip" \
    "${ANDROID_HOME}/platforms"

  # 2. Build Tools 36.0.0 + 35.0.0 (AGP needs both)
  download_and_extract \
    "${SDK_BASE_URL}/build-tools_r36_linux.zip" \
    "${ANDROID_HOME}/build-tools"
  if [ -d "${ANDROID_HOME}/build-tools/android-16" ] && [ ! -d "${ANDROID_HOME}/build-tools/36.0.0" ]; then
    mv "${ANDROID_HOME}/build-tools/android-16" "${ANDROID_HOME}/build-tools/36.0.0"
  fi
  download_and_extract \
    "${SDK_BASE_URL}/build-tools_r35_linux.zip" \
    "${ANDROID_HOME}/build-tools"
  if [ -d "${ANDROID_HOME}/build-tools/android-15" ] && [ ! -d "${ANDROID_HOME}/build-tools/35.0.0" ]; then
    mv "${ANDROID_HOME}/build-tools/android-15" "${ANDROID_HOME}/build-tools/35.0.0"
  fi

  # 3. Platform Tools (adb, fastboot)
  download_and_extract \
    "${SDK_BASE_URL}/platform-tools_r36.0.2-linux.zip" \
    "${ANDROID_HOME}"

  # 4. Command-line tools
  download_and_extract \
    "${SDK_BASE_URL}/commandlinetools-linux-11076708_latest.zip" \
    "${ANDROID_HOME}/cmdline-tools"
  if [ -d "${ANDROID_HOME}/cmdline-tools/cmdline-tools" ]; then
    mv "${ANDROID_HOME}/cmdline-tools/cmdline-tools" "${ANDROID_HOME}/cmdline-tools/latest"
  fi

  # 5. Accept SDK licenses
  mkdir -p "${ANDROID_HOME}/licenses"
  echo -e "\n24333f8a63b6825ea9c5514f83c2829b004d1fee" > "${ANDROID_HOME}/licenses/android-sdk-license"
  echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" >> "${ANDROID_HOME}/licenses/android-sdk-license"
  echo -e "\nd56f5187479451eabf01fb78af6dfcb131a6481e" >> "${ANDROID_HOME}/licenses/android-sdk-license"
  echo -e "\ne6b7c2ab7fa2298c15165e9583d0cbd0846b80b3" >> "${ANDROID_HOME}/licenses/android-sdk-license"
  echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "${ANDROID_HOME}/licenses/android-sdk-preview-license"

  echo "Android SDK installation complete."
}

if [ ! -d "${ANDROID_HOME}/platforms/android-36" ] || \
   [ ! -d "${ANDROID_HOME}/build-tools" ] || \
   [ ! -d "${ANDROID_HOME}/platform-tools" ]; then
  install_android_sdk
else
  echo "Android SDK already installed, skipping."
fi

# ── Gradle Distribution Setup ──────────────────────────────────────
# Pre-populate the Gradle wrapper cache via curl.
GRADLE_VERSION="8.13"
GRADLE_USER_HOME="${GRADLE_USER_HOME:-${HOME}/.gradle}"
GRADLE_DIST_URL="https://services.gradle.org/distributions/gradle-${GRADLE_VERSION}-bin.zip"
GRADLE_CACHE_HASH=$(python3 -c "
import hashlib
url = '${GRADLE_DIST_URL}'
md5 = hashlib.md5(url.encode('utf-8')).digest()
num = int.from_bytes(md5, byteorder='big')
digits = '0123456789abcdefghijklmnopqrstuvwxyz'
result = ''
while num > 0:
    result = digits[num % 36] + result
    num //= 36
print(result)
")
GRADLE_CACHE_DIR="${GRADLE_USER_HOME}/wrapper/dists/gradle-${GRADLE_VERSION}-bin/${GRADLE_CACHE_HASH}"

if [ ! -f "${GRADLE_CACHE_DIR}/gradle-${GRADLE_VERSION}-bin.zip.ok" ]; then
  echo "Pre-caching Gradle ${GRADLE_VERSION} distribution..."
  mkdir -p "${GRADLE_CACHE_DIR}"
  curl -fsSL -o "${GRADLE_CACHE_DIR}/gradle-${GRADLE_VERSION}-bin.zip" "${GRADLE_DIST_URL}"
  unzip -q -o "${GRADLE_CACHE_DIR}/gradle-${GRADLE_VERSION}-bin.zip" -d "${GRADLE_CACHE_DIR}/"
  touch "${GRADLE_CACHE_DIR}/gradle-${GRADLE_VERSION}-bin.zip.ok"
  touch "${GRADLE_CACHE_DIR}/gradle-${GRADLE_VERSION}-bin.zip.lck"
  echo "Gradle distribution cached."
else
  echo "Gradle distribution already cached, skipping."
fi

# ── Gradle Wrapper JAR ─────────────────────────────────────────────
if [ -n "${CLAUDE_PROJECT_DIR:-}" ] && [ ! -f "${CLAUDE_PROJECT_DIR}/gradle/wrapper/gradle-wrapper.jar" ]; then
  echo "Downloading missing gradle-wrapper.jar..."
  curl -fsSL -o "${CLAUDE_PROJECT_DIR}/gradle/wrapper/gradle-wrapper.jar" \
    "https://raw.githubusercontent.com/gradle/gradle/v${GRADLE_VERSION}.0/gradle/wrapper/gradle-wrapper.jar"
fi

# ── Robolectric Offline Dependencies ────────────────────────────────
# Robolectric downloads Android framework JARs at test-time via Java HTTP,
# which fails through the proxy. Pre-download them via curl.
ROBO_DIR="${HOME}/.robolectric-deps"
ROBO_BASE="https://repo1.maven.org/maven2/org/robolectric/android-all-instrumented"

if [ ! -f "${ROBO_DIR}/android-all-instrumented-10-robolectric-5803371-i7.jar" ]; then
  echo "Pre-caching Robolectric instrumented JARs..."
  mkdir -p "${ROBO_DIR}"
  # API 29 (Q) — used by most tests via @Config(sdk = [Q])
  curl -fsSL -o "${ROBO_DIR}/android-all-instrumented-10-robolectric-5803371-i7.jar" \
    "${ROBO_BASE}/10-robolectric-5803371-i7/android-all-instrumented-10-robolectric-5803371-i7.jar"
  # API 35 (Android 15) — matches compileSdk 36, Robolectric resolves to this
  curl -fsSL -o "${ROBO_DIR}/android-all-instrumented-15-robolectric-12650502-i7.jar" \
    "${ROBO_BASE}/15-robolectric-12650502-i7/android-all-instrumented-15-robolectric-12650502-i7.jar"
  # API 21 (Lollipop) — Robolectric default for some modules
  curl -fsSL -o "${ROBO_DIR}/android-all-instrumented-5.0.2_r3-robolectric-r0-i7.jar" \
    "${ROBO_BASE}/5.0.2_r3-robolectric-r0-i7/android-all-instrumented-5.0.2_r3-robolectric-r0-i7.jar"
  echo "Robolectric JARs cached."
else
  echo "Robolectric JARs already cached, skipping."
fi

# ── Export environment variables for the session ────────────────────
cat >> "${CLAUDE_ENV_FILE}" <<ENVEOF
export ANDROID_HOME="${ANDROID_HOME}"
export ANDROID_SDK_ROOT="${ANDROID_HOME}"
export PATH="${ANDROID_HOME}/cmdline-tools/latest/bin:${ANDROID_HOME}/platform-tools:\${PATH}"
ENVEOF

export ANDROID_HOME
export ANDROID_SDK_ROOT="${ANDROID_HOME}"
export PATH="${ANDROID_HOME}/cmdline-tools/latest/bin:${ANDROID_HOME}/platform-tools:${PATH}"

# ── local.properties ───────────────────────────────────────────────
# Create local.properties so AGP finds the SDK without env var issues
if [ -n "${CLAUDE_PROJECT_DIR:-}" ] && [ ! -f "${CLAUDE_PROJECT_DIR}/local.properties" ]; then
  echo "sdk.dir=${ANDROID_HOME}" > "${CLAUDE_PROJECT_DIR}/local.properties"
fi

# ── Warm Gradle wrapper ────────────────────────────────────────────
if [ -n "${CLAUDE_PROJECT_DIR:-}" ] && [ -f "${CLAUDE_PROJECT_DIR}/gradlew" ]; then
  echo "Warming up Gradle wrapper..."
  "${CLAUDE_PROJECT_DIR}/gradlew" -p "${CLAUDE_PROJECT_DIR}" --version > /dev/null 2>&1 || true
fi

echo "Session environment ready."
